### ISSUE TITLE
Double clicking tableau pile issue

### ISSUE THREAD

**Issue by yashpatel95** [char-e/CST8334---Software-Dev.-Project-#17]
Environment:
QA

Priority:
Medium

Steps to reproduce:
Have the foundation filled up to a point where there is some cards on the tableau pile that could be put on the foundation pile (but has cards beneath it) and then double click on the card.

Here we see that we have 5 of diamonds in the foundation pile and 6 of diamonds in the tableau pile. 
![image](https://user-images.githubusercontent.com/77603118/123883106-441a1500-d916-11eb-941c-15bc7a6191b9.png)

Double clicking the 6 of diamonds moves it to the foundation pile when it shouldn't.
![image](https://user-images.githubusercontent.com/77603118/123883126-5a27d580-d916-11eb-98c6-f92400b02a96.png)

Expected Result:
Only the last card of each tableau pile should be able to move to foundation pile.

Actual Result:
Cards in the middle of tableau pile moves to the foundation.

**Comment by blueboyfury28** [comment]
Idk if you fixed it yet but In the magic move function after the line of code that says **Let cardSelected = event.target;** … add this line of code **If(cardSelected.nextSibling !== null) return;**…that should fix it
