### ISSUE TITLE
Stockpile doesn't get restocked when playing in Vegas mode

### ISSUE THREAD

**Issue by eknikolaeva** [char-e/CST8334---Software-Dev.-Project-#31]
**Environment:**
QA

**Priority:**
High

**Steps to reproduce:**

1. Turn on Vegas Mode.
2. Click on the stockpile until all cards have been moved to the waste. 
3. Click on the stockpile to restock the cards.

**Expected result:**
Stockpile is restocked.

**Actual result:**
Stockpile isn't restocked.

**Comment by demo0033** [comment]
Vegas rules only allow one pass through the stock, after which the game ends intentionally.
